/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.degreeclasscalcv5;

/**
 *
 * @author jameswoodthorpe
 */
public class DegreeClassCalcV5 extends javax.swing.JFrame {

    /**
     * Creates new form window
     */
    public DegreeClassCalcV5() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        level5InputAreaPanel = new javax.swing.JPanel();
        L5CredInp1 = new javax.swing.JTextField();
        L5ModInp1 = new javax.swing.JTextField();
        L5MarkInp1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        L5ModInp2 = new javax.swing.JTextField();
        L5CredInp2 = new javax.swing.JTextField();
        L5MarkInp2 = new javax.swing.JTextField();
        L5ModInp3 = new javax.swing.JTextField();
        L5CredInp3 = new javax.swing.JTextField();
        L5MarkInp3 = new javax.swing.JTextField();
        L5ModInp4 = new javax.swing.JTextField();
        L5CredInp4 = new javax.swing.JTextField();
        L5MarkInp4 = new javax.swing.JTextField();
        L5ModInp5 = new javax.swing.JTextField();
        L5CredInp5 = new javax.swing.JTextField();
        L5MarkInp5 = new javax.swing.JTextField();
        L5ModInp6 = new javax.swing.JTextField();
        L5CredInp6 = new javax.swing.JTextField();
        L5MarkInp6 = new javax.swing.JTextField();
        L5ModInp7 = new javax.swing.JTextField();
        L5CredInp7 = new javax.swing.JTextField();
        L5MarkInp7 = new javax.swing.JTextField();
        L5ModInp8 = new javax.swing.JTextField();
        L5CredInp8 = new javax.swing.JTextField();
        L5MarkInp8 = new javax.swing.JTextField();
        L5ModInp9 = new javax.swing.JTextField();
        L5CredInp9 = new javax.swing.JTextField();
        L5MarkInp9 = new javax.swing.JTextField();
        L5ModInp10 = new javax.swing.JTextField();
        L5CredInp10 = new javax.swing.JTextField();
        L5MarkInp10 = new javax.swing.JTextField();
        L5TitleLabel = new javax.swing.JLabel();
        Level5Button = new javax.swing.JButton();
        level6InputAreaPanel = new javax.swing.JPanel();
        L6CredInp1 = new javax.swing.JTextField();
        L6ModInp1 = new javax.swing.JTextField();
        L6MarkInp1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        L6ModInp2 = new javax.swing.JTextField();
        L6CredInp2 = new javax.swing.JTextField();
        L6MarkInp2 = new javax.swing.JTextField();
        L6ModInp3 = new javax.swing.JTextField();
        L6CredInp3 = new javax.swing.JTextField();
        L6MarkInp3 = new javax.swing.JTextField();
        L6ModInp4 = new javax.swing.JTextField();
        L6CredInp4 = new javax.swing.JTextField();
        L6MarkInp4 = new javax.swing.JTextField();
        L6ModInp5 = new javax.swing.JTextField();
        L6CredInp5 = new javax.swing.JTextField();
        L6MarkInp5 = new javax.swing.JTextField();
        L6ModInp6 = new javax.swing.JTextField();
        L6CredInp6 = new javax.swing.JTextField();
        L6MarkInp6 = new javax.swing.JTextField();
        L6ModInp7 = new javax.swing.JTextField();
        L6CredInp7 = new javax.swing.JTextField();
        L6MarkInp7 = new javax.swing.JTextField();
        L6ModInp8 = new javax.swing.JTextField();
        L6CredInp8 = new javax.swing.JTextField();
        L6MarkInp8 = new javax.swing.JTextField();
        L6ModInp9 = new javax.swing.JTextField();
        L6CredInp9 = new javax.swing.JTextField();
        L6MarkInp9 = new javax.swing.JTextField();
        L6ModInp10 = new javax.swing.JTextField();
        L6CredInp10 = new javax.swing.JTextField();
        L6MarkInp10 = new javax.swing.JTextField();
        L6TitleLabel = new javax.swing.JLabel();
        resultsPanel = new javax.swing.JPanel();
        MethodAResultsLabel = new javax.swing.JLabel();
        MethodBResultsLabel = new javax.swing.JLabel();
        MethodCResultsLabel = new javax.swing.JLabel();
        MethodDResultsLabel = new javax.swing.JLabel();
        MethodAResultsOutput = new javax.swing.JTextField();
        MethodBResultsOutput = new javax.swing.JTextField();
        MethodCResultsOutput = new javax.swing.JTextField();
        MethodDResultsOutput = new javax.swing.JTextField();
        calcButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        homeButton.setBackground(new java.awt.Color(154, 217, 255));
        homeButton.setForeground(new java.awt.Color(0, 0, 0));
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        quitButton.setBackground(new java.awt.Color(233, 66, 66));
        quitButton.setForeground(new java.awt.Color(0, 0, 0));
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        level5InputAreaPanel.setBackground(new java.awt.Color(154, 217, 255));

        L5CredInp1.setBackground(new java.awt.Color(255, 255, 255));
        L5CredInp1.setForeground(new java.awt.Color(0, 0, 0));

        L5ModInp1.setBackground(new java.awt.Color(255, 255, 255));
        L5ModInp1.setForeground(new java.awt.Color(0, 0, 0));
        L5ModInp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L5ModInp1ActionPerformed(evt);
            }
        });

        L5MarkInp1.setBackground(new java.awt.Color(255, 255, 255));
        L5MarkInp1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Module");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Credits");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Mark");

        L5ModInp2.setBackground(new java.awt.Color(255, 255, 255));
        L5ModInp2.setForeground(new java.awt.Color(0, 0, 0));

        L5CredInp2.setBackground(new java.awt.Color(255, 255, 255));
        L5CredInp2.setForeground(new java.awt.Color(0, 0, 0));

        L5MarkInp2.setBackground(new java.awt.Color(255, 255, 255));
        L5MarkInp2.setForeground(new java.awt.Color(0, 0, 0));

        L5ModInp3.setBackground(new java.awt.Color(255, 255, 255));
        L5ModInp3.setForeground(new java.awt.Color(0, 0, 0));

        L5CredInp3.setBackground(new java.awt.Color(255, 255, 255));
        L5CredInp3.setForeground(new java.awt.Color(0, 0, 0));

        L5MarkInp3.setBackground(new java.awt.Color(255, 255, 255));
        L5MarkInp3.setForeground(new java.awt.Color(0, 0, 0));

        L5ModInp4.setBackground(new java.awt.Color(255, 255, 255));
        L5ModInp4.setForeground(new java.awt.Color(0, 0, 0));

        L5CredInp4.setBackground(new java.awt.Color(255, 255, 255));
        L5CredInp4.setForeground(new java.awt.Color(0, 0, 0));

        L5MarkInp4.setBackground(new java.awt.Color(255, 255, 255));
        L5MarkInp4.setForeground(new java.awt.Color(0, 0, 0));

        L5ModInp5.setBackground(new java.awt.Color(255, 255, 255));
        L5ModInp5.setForeground(new java.awt.Color(0, 0, 0));

        L5CredInp5.setBackground(new java.awt.Color(255, 255, 255));
        L5CredInp5.setForeground(new java.awt.Color(0, 0, 0));

        L5MarkInp5.setBackground(new java.awt.Color(255, 255, 255));
        L5MarkInp5.setForeground(new java.awt.Color(0, 0, 0));

        L5ModInp6.setBackground(new java.awt.Color(255, 255, 255));
        L5ModInp6.setForeground(new java.awt.Color(0, 0, 0));

        L5CredInp6.setBackground(new java.awt.Color(255, 255, 255));
        L5CredInp6.setForeground(new java.awt.Color(0, 0, 0));

        L5MarkInp6.setBackground(new java.awt.Color(255, 255, 255));
        L5MarkInp6.setForeground(new java.awt.Color(0, 0, 0));

        L5ModInp7.setBackground(new java.awt.Color(255, 255, 255));
        L5ModInp7.setForeground(new java.awt.Color(0, 0, 0));

        L5CredInp7.setBackground(new java.awt.Color(255, 255, 255));
        L5CredInp7.setForeground(new java.awt.Color(0, 0, 0));

        L5MarkInp7.setBackground(new java.awt.Color(255, 255, 255));
        L5MarkInp7.setForeground(new java.awt.Color(0, 0, 0));

        L5ModInp8.setBackground(new java.awt.Color(255, 255, 255));
        L5ModInp8.setForeground(new java.awt.Color(0, 0, 0));

        L5CredInp8.setBackground(new java.awt.Color(255, 255, 255));
        L5CredInp8.setForeground(new java.awt.Color(0, 0, 0));

        L5MarkInp8.setBackground(new java.awt.Color(255, 255, 255));
        L5MarkInp8.setForeground(new java.awt.Color(0, 0, 0));

        L5ModInp9.setBackground(new java.awt.Color(255, 255, 255));
        L5ModInp9.setForeground(new java.awt.Color(0, 0, 0));

        L5CredInp9.setBackground(new java.awt.Color(255, 255, 255));
        L5CredInp9.setForeground(new java.awt.Color(0, 0, 0));

        L5MarkInp9.setBackground(new java.awt.Color(255, 255, 255));
        L5MarkInp9.setForeground(new java.awt.Color(0, 0, 0));

        L5ModInp10.setBackground(new java.awt.Color(255, 255, 255));
        L5ModInp10.setForeground(new java.awt.Color(0, 0, 0));

        L5CredInp10.setBackground(new java.awt.Color(255, 255, 255));
        L5CredInp10.setForeground(new java.awt.Color(0, 0, 0));

        L5MarkInp10.setBackground(new java.awt.Color(255, 255, 255));
        L5MarkInp10.setForeground(new java.awt.Color(0, 0, 0));

        L5TitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        L5TitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        L5TitleLabel.setText("Level 5");

        javax.swing.GroupLayout level5InputAreaPanelLayout = new javax.swing.GroupLayout(level5InputAreaPanel);
        level5InputAreaPanel.setLayout(level5InputAreaPanelLayout);
        level5InputAreaPanelLayout.setHorizontalGroup(
            level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                            .addComponent(L5ModInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5CredInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5MarkInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                            .addComponent(L5ModInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5CredInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5MarkInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(jLabel2)
                            .addGap(128, 128, 128)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addGap(70, 70, 70)))
                    .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                            .addComponent(L5ModInp4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5CredInp4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5MarkInp4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                            .addComponent(L5ModInp3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5CredInp3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5MarkInp3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                            .addComponent(L5ModInp5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5CredInp5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5MarkInp5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                            .addComponent(L5ModInp6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5CredInp6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5MarkInp6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                            .addComponent(L5ModInp8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5CredInp8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5MarkInp8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                            .addComponent(L5ModInp7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5CredInp7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5MarkInp7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                            .addComponent(L5ModInp9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5CredInp9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5MarkInp9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                            .addComponent(L5ModInp10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5CredInp10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(L5MarkInp10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, level5InputAreaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L5TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
        );
        level5InputAreaPanelLayout.setVerticalGroup(
            level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(level5InputAreaPanelLayout.createSequentialGroup()
                .addComponent(L5TitleLabel)
                .addGap(11, 11, 11)
                .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L5CredInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5ModInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5MarkInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L5CredInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5ModInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5MarkInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L5CredInp3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5ModInp3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5MarkInp3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L5CredInp4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5ModInp4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5MarkInp4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L5CredInp5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5ModInp5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5MarkInp5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L5CredInp6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5ModInp6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5MarkInp6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L5CredInp7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5ModInp7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5MarkInp7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L5CredInp8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5ModInp8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5MarkInp8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L5CredInp9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5ModInp9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5MarkInp9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level5InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L5CredInp10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5ModInp10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5MarkInp10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Level5Button.setBackground(new java.awt.Color(154, 217, 255));
        Level5Button.setForeground(new java.awt.Color(0, 0, 0));
        Level5Button.setText("Level 5");
        Level5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level5ButtonActionPerformed(evt);
            }
        });

        level6InputAreaPanel.setBackground(new java.awt.Color(154, 217, 255));

        L6CredInp1.setBackground(new java.awt.Color(255, 255, 255));
        L6CredInp1.setForeground(new java.awt.Color(0, 0, 0));

        L6ModInp1.setBackground(new java.awt.Color(255, 255, 255));
        L6ModInp1.setForeground(new java.awt.Color(0, 0, 0));

        L6MarkInp1.setBackground(new java.awt.Color(255, 255, 255));
        L6MarkInp1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Module");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Credits");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Mark");

        L6ModInp2.setBackground(new java.awt.Color(255, 255, 255));
        L6ModInp2.setForeground(new java.awt.Color(0, 0, 0));

        L6CredInp2.setBackground(new java.awt.Color(255, 255, 255));
        L6CredInp2.setForeground(new java.awt.Color(0, 0, 0));

        L6MarkInp2.setBackground(new java.awt.Color(255, 255, 255));
        L6MarkInp2.setForeground(new java.awt.Color(0, 0, 0));

        L6ModInp3.setBackground(new java.awt.Color(255, 255, 255));
        L6ModInp3.setForeground(new java.awt.Color(0, 0, 0));

        L6CredInp3.setBackground(new java.awt.Color(255, 255, 255));
        L6CredInp3.setForeground(new java.awt.Color(0, 0, 0));

        L6MarkInp3.setBackground(new java.awt.Color(255, 255, 255));
        L6MarkInp3.setForeground(new java.awt.Color(0, 0, 0));

        L6ModInp4.setBackground(new java.awt.Color(255, 255, 255));
        L6ModInp4.setForeground(new java.awt.Color(0, 0, 0));

        L6CredInp4.setBackground(new java.awt.Color(255, 255, 255));
        L6CredInp4.setForeground(new java.awt.Color(0, 0, 0));

        L6MarkInp4.setBackground(new java.awt.Color(255, 255, 255));
        L6MarkInp4.setForeground(new java.awt.Color(0, 0, 0));

        L6ModInp5.setBackground(new java.awt.Color(255, 255, 255));
        L6ModInp5.setForeground(new java.awt.Color(0, 0, 0));

        L6CredInp5.setBackground(new java.awt.Color(255, 255, 255));
        L6CredInp5.setForeground(new java.awt.Color(0, 0, 0));

        L6MarkInp5.setBackground(new java.awt.Color(255, 255, 255));
        L6MarkInp5.setForeground(new java.awt.Color(0, 0, 0));

        L6ModInp6.setBackground(new java.awt.Color(255, 255, 255));
        L6ModInp6.setForeground(new java.awt.Color(0, 0, 0));

        L6CredInp6.setBackground(new java.awt.Color(255, 255, 255));
        L6CredInp6.setForeground(new java.awt.Color(0, 0, 0));

        L6MarkInp6.setBackground(new java.awt.Color(255, 255, 255));
        L6MarkInp6.setForeground(new java.awt.Color(0, 0, 0));

        L6ModInp7.setBackground(new java.awt.Color(255, 255, 255));
        L6ModInp7.setForeground(new java.awt.Color(0, 0, 0));

        L6CredInp7.setBackground(new java.awt.Color(255, 255, 255));
        L6CredInp7.setForeground(new java.awt.Color(0, 0, 0));

        L6MarkInp7.setBackground(new java.awt.Color(255, 255, 255));
        L6MarkInp7.setForeground(new java.awt.Color(0, 0, 0));

        L6ModInp8.setBackground(new java.awt.Color(255, 255, 255));
        L6ModInp8.setForeground(new java.awt.Color(0, 0, 0));

        L6CredInp8.setBackground(new java.awt.Color(255, 255, 255));
        L6CredInp8.setForeground(new java.awt.Color(0, 0, 0));

        L6MarkInp8.setBackground(new java.awt.Color(255, 255, 255));
        L6MarkInp8.setForeground(new java.awt.Color(0, 0, 0));

        L6ModInp9.setBackground(new java.awt.Color(255, 255, 255));
        L6ModInp9.setForeground(new java.awt.Color(0, 0, 0));

        L6CredInp9.setBackground(new java.awt.Color(255, 255, 255));
        L6CredInp9.setForeground(new java.awt.Color(0, 0, 0));

        L6MarkInp9.setBackground(new java.awt.Color(255, 255, 255));
        L6MarkInp9.setForeground(new java.awt.Color(0, 0, 0));

        L6ModInp10.setBackground(new java.awt.Color(255, 255, 255));
        L6ModInp10.setForeground(new java.awt.Color(0, 0, 0));

        L6CredInp10.setBackground(new java.awt.Color(255, 255, 255));
        L6CredInp10.setForeground(new java.awt.Color(0, 0, 0));

        L6MarkInp10.setBackground(new java.awt.Color(255, 255, 255));
        L6MarkInp10.setForeground(new java.awt.Color(0, 0, 0));

        L6TitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        L6TitleLabel.setForeground(new java.awt.Color(0, 0, 0));
        L6TitleLabel.setText("Level 6");

        javax.swing.GroupLayout level6InputAreaPanelLayout = new javax.swing.GroupLayout(level6InputAreaPanel);
        level6InputAreaPanel.setLayout(level6InputAreaPanelLayout);
        level6InputAreaPanelLayout.setHorizontalGroup(
            level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                                    .addComponent(L6ModInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6CredInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6MarkInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                                    .addComponent(L6ModInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6CredInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6MarkInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addComponent(jLabel6)
                                    .addGap(128, 128, 128)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addGap(70, 70, 70)))
                            .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                                    .addComponent(L6ModInp4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6CredInp4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6MarkInp4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                                    .addComponent(L6ModInp3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6CredInp3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6MarkInp3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                                    .addComponent(L6ModInp5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6CredInp5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6MarkInp5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                                    .addComponent(L6ModInp6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6CredInp6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6MarkInp6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                                    .addComponent(L6ModInp8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6CredInp8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6MarkInp8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                                    .addComponent(L6ModInp7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6CredInp7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6MarkInp7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                                    .addComponent(L6ModInp9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6CredInp9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6MarkInp9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                                    .addComponent(L6ModInp10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6CredInp10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L6MarkInp10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(L6TitleLabel)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        level6InputAreaPanelLayout.setVerticalGroup(
            level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(level6InputAreaPanelLayout.createSequentialGroup()
                .addComponent(L6TitleLabel)
                .addGap(17, 17, 17)
                .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L6CredInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6ModInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6MarkInp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L6CredInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6ModInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6MarkInp2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L6CredInp3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6ModInp3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6MarkInp3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L6CredInp4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6ModInp4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6MarkInp4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L6CredInp5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6ModInp5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6MarkInp5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L6CredInp6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6ModInp6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6MarkInp6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L6CredInp7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6ModInp7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6MarkInp7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L6CredInp8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6ModInp8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6MarkInp8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L6CredInp9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6ModInp9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6MarkInp9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(level6InputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L6CredInp10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6ModInp10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6MarkInp10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        resultsPanel.setBackground(new java.awt.Color(154, 217, 255));

        MethodAResultsLabel.setForeground(new java.awt.Color(0, 0, 0));
        MethodAResultsLabel.setText("Method A");

        MethodBResultsLabel.setForeground(new java.awt.Color(0, 0, 0));
        MethodBResultsLabel.setText("Method B");

        MethodCResultsLabel.setForeground(new java.awt.Color(0, 0, 0));
        MethodCResultsLabel.setText("Method C");

        MethodDResultsLabel.setForeground(new java.awt.Color(0, 0, 0));
        MethodDResultsLabel.setText("Method D");

        MethodAResultsOutput.setBackground(new java.awt.Color(255, 255, 255));
        MethodAResultsOutput.setForeground(new java.awt.Color(0, 0, 0));
        MethodAResultsOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MethodAResultsOutputActionPerformed(evt);
            }
        });

        MethodBResultsOutput.setBackground(new java.awt.Color(255, 255, 255));
        MethodBResultsOutput.setForeground(new java.awt.Color(0, 0, 0));

        MethodCResultsOutput.setBackground(new java.awt.Color(255, 255, 255));
        MethodCResultsOutput.setForeground(new java.awt.Color(0, 0, 0));

        MethodDResultsOutput.setBackground(new java.awt.Color(255, 255, 255));
        MethodDResultsOutput.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout resultsPanelLayout = new javax.swing.GroupLayout(resultsPanel);
        resultsPanel.setLayout(resultsPanelLayout);
        resultsPanelLayout.setHorizontalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addComponent(MethodBResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MethodBResultsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MethodDResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addComponent(MethodAResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MethodAResultsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(MethodCResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MethodCResultsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MethodDResultsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        resultsPanelLayout.setVerticalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MethodAResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MethodCResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MethodAResultsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MethodCResultsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MethodBResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MethodDResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MethodBResultsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MethodDResultsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        calcButton.setText("Calculate");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setText("Degree Class Estimator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Level5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addComponent(resultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(level5InputAreaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(level6InputAreaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(598, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(631, 631, 631))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(547, 547, 547))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(level5InputAreaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(level6InputAreaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Level5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void Level5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level5ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Level5ButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void L5ModInp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L5ModInp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L5ModInp1ActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        // TODO add your handling code here:
        dataCollection();
        
        MethodAResultsOutput.setText(MethodAResultsOutput.getText().toUpperCase());
        MethodAResultsOutput.setEditable(false);
            
        // couldnt get the results to output when using the calculate button ^

    }//GEN-LAST:event_calcButtonActionPerformed

    private void MethodAResultsOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MethodAResultsOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MethodAResultsOutputActionPerformed
    
    
    
    
    public void dataCollection() {
        // l5 credit data collection
        int L5Cred1 = Integer.parseInt(L5CredInp1.getText());
        int L5Cred2 = Integer.parseInt(L5CredInp2.getText());
        int L5Cred3 = Integer.parseInt(L5CredInp3.getText());
        int L5Cred4 = Integer.parseInt(L5CredInp4.getText());
        int L5Cred5 = Integer.parseInt(L5CredInp5.getText());
        int L5Cred6 = Integer.parseInt(L5CredInp6.getText());
        int L5Cred7 = Integer.parseInt(L5CredInp7.getText());
        int L5Cred8 = Integer.parseInt(L5CredInp8.getText());
        int L5Cred9 = Integer.parseInt(L5CredInp9.getText());
        int L5Cred10 = Integer.parseInt(L5CredInp10.getText());
        
        //l5 mark data collection
        int L5Mark1 = Integer.parseInt(L5MarkInp1.getText());
        int L5Mark2 = Integer.parseInt(L5MarkInp2.getText());
        int L5Mark3 = Integer.parseInt(L5MarkInp3.getText());
        int L5Mark4 = Integer.parseInt(L5MarkInp4.getText());
        int L5Mark5 = Integer.parseInt(L5MarkInp5.getText());
        int L5Mark6 = Integer.parseInt(L5MarkInp6.getText());
        int L5Mark7 = Integer.parseInt(L5MarkInp7.getText());
        int L5Mark8 = Integer.parseInt(L5MarkInp8.getText());
        int L5Mark9 = Integer.parseInt(L5MarkInp9.getText());
        int L5Mark10 = Integer.parseInt(L5MarkInp10.getText());
        
        
        //l6 credit data collection
        int L6Cred1 = Integer.parseInt(L6CredInp1.getText());
        int L6Cred2 = Integer.parseInt(L6CredInp2.getText());
        int L6Cred3 = Integer.parseInt(L6CredInp3.getText());
        int L6Cred4 = Integer.parseInt(L6CredInp4.getText());
        int L6Cred5 = Integer.parseInt(L6CredInp5.getText());
        int L6Cred6 = Integer.parseInt(L6CredInp6.getText());
        int L6Cred7 = Integer.parseInt(L6CredInp7.getText());
        int L6Cred8 = Integer.parseInt(L6CredInp8.getText());
        int L6Cred9 = Integer.parseInt(L6CredInp9.getText());
        int L6Cred10 = Integer.parseInt(L6CredInp10.getText());
        
        //l6 mark data collection
        int L6Mark1 = Integer.parseInt(L6MarkInp1.getText());
        int L6Mark2 = Integer.parseInt(L6MarkInp2.getText());
        int L6Mark3 = Integer.parseInt(L6MarkInp3.getText());
        int L6Mark4 = Integer.parseInt(L6MarkInp4.getText());
        int L6Mark5 = Integer.parseInt(L6MarkInp5.getText());
        int L6Mark6 = Integer.parseInt(L6MarkInp6.getText());
        int L6Mark7 = Integer.parseInt(L6MarkInp7.getText());
        int L6Mark8 = Integer.parseInt(L6MarkInp8.getText());
        int L6Mark9 = Integer.parseInt(L6MarkInp9.getText());
        int L6Mark10 = Integer.parseInt(L6MarkInp10.getText());
        
        //arrays to store the user inputs
        int[] L5Credits = {L5Cred1, L5Cred2, L5Cred3, L5Cred4, L5Cred5, L5Cred6,
            L5Cred7, L5Cred8, L5Cred9, L5Cred10};
        int[] L5Marks = {L5Mark1, L5Mark2, L5Mark3, L5Mark4, L5Mark5, L5Mark6,
            L5Mark7, L5Mark8, L5Mark9, L5Mark10};
        
        int[] L6Credits = {L6Cred1, L6Cred2, L6Cred3, L6Cred4, L6Cred5, L6Cred6,
            L6Cred7, L6Cred8, L6Cred9, L6Cred10};
        int[] L6Marks = {L6Mark1, L6Mark2, L6Mark3, L6Mark4, L6Mark5, L6Mark6,
            L6Mark7, L6Mark8, L6Mark9, L6Mark10};
        
        // converts the integer values to double
        double[] L5MarksDouble = convertToDoubleArray(L5Marks);
        double[] L6MarksDouble = convertToDoubleArray(L6Marks);
        
        // calculates the results 
        double resultL5 = calcMethA(L5Credits, L5MarksDouble);
        double resultL6 = calcMethA(L6Credits, L6MarksDouble);
        
        
        
        
    }
    
    // method to convert double to integer
    private double[] convertToDoubleArray(int[] intArray) {
        double[] doubleArray = new double[intArray.length];
        for (int i = 0; i < intArray.length; i++) {
            doubleArray[i] = intArray[i];
        }
        return doubleArray;
    }
    
    
    
    
    //calculation for method a 
    private static double calcMethA(int[] credits, double[] marks) {
        double weightedSum = 0;
        int totalCredits = 0;
        
        
        for (int i = 0; i < credits.length; i++) {
            weightedSum += credits[i] * marks[i];
            totalCredits += credits[i];
        }
        
        return weightedSum / totalCredits;
    }
    
    // calculation for methodb
    private static double calcMethB(int[] credits, double[] marks) {
        double weightedSum = 0;
        int totalCredits = 0;

        for (int i = 0; i < credits.length; i++) {
            weightedSum += credits[i] * marks[i];
            totalCredits += credits[i];
        }

        return weightedSum / totalCredits;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DegreeClassCalcV5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DegreeClassCalcV5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DegreeClassCalcV5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DegreeClassCalcV5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DegreeClassCalcV5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField L5CredInp1;
    private javax.swing.JTextField L5CredInp10;
    private javax.swing.JTextField L5CredInp2;
    private javax.swing.JTextField L5CredInp3;
    private javax.swing.JTextField L5CredInp4;
    private javax.swing.JTextField L5CredInp5;
    private javax.swing.JTextField L5CredInp6;
    private javax.swing.JTextField L5CredInp7;
    private javax.swing.JTextField L5CredInp8;
    private javax.swing.JTextField L5CredInp9;
    private javax.swing.JTextField L5MarkInp1;
    private javax.swing.JTextField L5MarkInp10;
    private javax.swing.JTextField L5MarkInp2;
    private javax.swing.JTextField L5MarkInp3;
    private javax.swing.JTextField L5MarkInp4;
    private javax.swing.JTextField L5MarkInp5;
    private javax.swing.JTextField L5MarkInp6;
    private javax.swing.JTextField L5MarkInp7;
    private javax.swing.JTextField L5MarkInp8;
    private javax.swing.JTextField L5MarkInp9;
    private javax.swing.JTextField L5ModInp1;
    private javax.swing.JTextField L5ModInp10;
    private javax.swing.JTextField L5ModInp2;
    private javax.swing.JTextField L5ModInp3;
    private javax.swing.JTextField L5ModInp4;
    private javax.swing.JTextField L5ModInp5;
    private javax.swing.JTextField L5ModInp6;
    private javax.swing.JTextField L5ModInp7;
    private javax.swing.JTextField L5ModInp8;
    private javax.swing.JTextField L5ModInp9;
    private javax.swing.JLabel L5TitleLabel;
    private javax.swing.JTextField L6CredInp1;
    private javax.swing.JTextField L6CredInp10;
    private javax.swing.JTextField L6CredInp2;
    private javax.swing.JTextField L6CredInp3;
    private javax.swing.JTextField L6CredInp4;
    private javax.swing.JTextField L6CredInp5;
    private javax.swing.JTextField L6CredInp6;
    private javax.swing.JTextField L6CredInp7;
    private javax.swing.JTextField L6CredInp8;
    private javax.swing.JTextField L6CredInp9;
    private javax.swing.JTextField L6MarkInp1;
    private javax.swing.JTextField L6MarkInp10;
    private javax.swing.JTextField L6MarkInp2;
    private javax.swing.JTextField L6MarkInp3;
    private javax.swing.JTextField L6MarkInp4;
    private javax.swing.JTextField L6MarkInp5;
    private javax.swing.JTextField L6MarkInp6;
    private javax.swing.JTextField L6MarkInp7;
    private javax.swing.JTextField L6MarkInp8;
    private javax.swing.JTextField L6MarkInp9;
    private javax.swing.JTextField L6ModInp1;
    private javax.swing.JTextField L6ModInp10;
    private javax.swing.JTextField L6ModInp2;
    private javax.swing.JTextField L6ModInp3;
    private javax.swing.JTextField L6ModInp4;
    private javax.swing.JTextField L6ModInp5;
    private javax.swing.JTextField L6ModInp6;
    private javax.swing.JTextField L6ModInp7;
    private javax.swing.JTextField L6ModInp8;
    private javax.swing.JTextField L6ModInp9;
    private javax.swing.JLabel L6TitleLabel;
    private javax.swing.JButton Level5Button;
    private javax.swing.JLabel MethodAResultsLabel;
    private javax.swing.JTextField MethodAResultsOutput;
    private javax.swing.JLabel MethodBResultsLabel;
    private javax.swing.JTextField MethodBResultsOutput;
    private javax.swing.JLabel MethodCResultsLabel;
    private javax.swing.JTextField MethodCResultsOutput;
    private javax.swing.JLabel MethodDResultsLabel;
    private javax.swing.JTextField MethodDResultsOutput;
    private javax.swing.JButton calcButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel level5InputAreaPanel;
    private javax.swing.JPanel level6InputAreaPanel;
    private javax.swing.JButton quitButton;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
